### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by petarov** [geometer/FBReaderJ-plugin-local-opds-scanner#2]
Hi,

I'm trying to use this plugin to open a Calibre OPDS catalog through a HTTPS connection using a [Let's Encrypt](https://letsencrypt.org/) SSL certificate. Sadly, this doesn't seem to work. 

```
10-10 21:37:23.264  9308 21023 W System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
10-10 21:37:23.269  9308 21023 W System.err:    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
10-10 21:37:23.269  9308 21023 W System.err:    at android.patches.b.createSocket(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
10-10 21:37:23.269  9308 21023 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.zlibrary.core.d.j.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.zlibrary.core.d.j.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.zlibrary.core.d.g.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.android.fbreader.network.auth.b.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.zlibrary.core.d.g.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.fbreader.network.q.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.fbreader.network.c.k.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.fbreader.network.c.k.a(Unknown Source)
10-10 21:37:23.269  9308 21023 W System.err:    at org.geometerplus.fbreader.network.f.c.b(Unknown Source)
10-10 21:37:23.270  9308 21023 W System.err:    at org.geometerplus.fbreader.network.f.k.run(Unknown Source)
10-10 21:37:23.270  9308 21023 W System.err:    at java.lang.Thread.run(Thread.java:818)
10-10 21:37:23.270  9308 21023 W System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
10-10 21:37:23.270  9308 21023 W System.err:    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
10-10 21:37:23.270  9308 21023 W System.err:    at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
10-10 21:37:23.270  9308 21023 W System.err:    at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
10-10 21:37:23.270  9308 21023 W System.err:    at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
10-10 21:37:23.270  9308 21023 W System.err:    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
10-10 21:37:23.270  9308 21023 W System.err:    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
10-10 21:37:23.270  9308 21023 W System.err:    ... 19 more
10-10 21:37:23.270  9308 21023 W System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
10-10 21:37:23.271  9308 21023 W System.err:    ... 25 more

```

Would it be an option to provide a path to trusted root certs when configuring the plugin?

**Comment by petarov** [comment]
Well, seems I was too quick to open an issue. After explicitly installing the [DST Root X3](https://letsencrypt.org/certificates/) certificate on my device (via Settings - Security), it all seems to work now. 🆒
